# Manifest for python-unicode-equivalence-lab
# 42 fixed cases with literal inputs and expected outputs.

CASES = [
    # 1
    {
        "id": "c01_empty_nfc",
        "operation": "normalize_text",
        "form": "NFC",
        "text": "",
        "expected_output": "",
        "expected_bool": None,
        "classification": "success",
        "observation": "empty string unchanged under NFC",
    },
    # 2
    {
        "id": "c02_ascii_all_forms",
        "operation": "normalize_text",
        "text": "Hello!",
        "all_forms": True,
        "expected_output": {
            "NFC": "Hello!",
            "NFD": "Hello!",
            "NFKC": "Hello!",
            "NFKD": "Hello!",
        },
        "expected_bool": None,
        "classification": "success",
        "observation": "ascii unchanged under all four forms",
    },
    # 3
    {
        "id": "c03_e_acute_decompose",
        "operation": "normalize_text",
        "form": "NFD",
        "text": "\u00e9",
        "expected_output": "e\u0301",
        "expected_bool": None,
        "classification": "success",
        "observation": "precomposed é decomposing under NFD",
        "codepoints_input": ("U+00E9",),
        "codepoints_output": ("U+0065", "U+0301"),
        "combining_classes": (0, 230),
    },
    # 4
    {
        "id": "c04_e_acute_compose",
        "operation": "normalize_text",
        "form": "NFC",
        "text": "e\u0301",
        "expected_output": "\u00e9",
        "expected_bool": None,
        "classification": "success",
        "observation": "e + U+0301 composing under NFC",
        "codepoints_input": ("U+0065", "U+0301"),
        "codepoints_output": ("U+00E9",),
    },
    # 5
    {
        "id": "c05_angstrom_sign_nfc",
        "operation": "normalize_text",
        "form": "NFC",
        "text": "\u212b",
        "expected_output": "\u00c5",
        "expected_bool": None,
        "classification": "success",
        "observation": "angstrom sign normalizing to U+00C5 under NFC",
        "codepoints_input": ("U+212B",),
        "codepoints_output": ("U+00C5",),
    },
    # 6
    {
        "id": "c06_ring_a_decompose",
        "operation": "normalize_text",
        "form": "NFD",
        "text": "\u00c5",
        "expected_output": "A\u030a",
        "expected_bool": None,
        "classification": "success",
        "observation": "U+00C5 decomposing to A + U+030A under NFD",
        "codepoints_input": ("U+00C5",),
        "codepoints_output": ("U+0041", "U+030A"),
    },
    # 7
    {
        "id": "c07_ligature_ffi_canonical_distinct",
        "operation": "canonical_equal",
        "left": "\ufb03",
        "right": "ffi",
        "expected_output": None,
        "expected_bool": False,
        "classification": "canonical_distinct",
        "observation": "ligature U+FB03 staying distinct from ffi under NFC",
        "codepoints_left": ("U+FB03",),
        "codepoints_right": ("U+0066", "U+0066", "U+0069"),
    },
    # 8
    {
        "id": "c08_ligature_ffi_compat_equal",
        "operation": "compatibility_equal",
        "left": "\ufb03",
        "right": "ffi",
        "expected_output": None,
        "expected_bool": True,
        "classification": "compatibility_equal",
        "observation": "the same ligature becoming ffi under NFKC",
        "codepoints_left": ("U+FB03",),
        "codepoints_right": ("U+0066", "U+0066", "U+0069"),
    },
    # 9
    {
        "id": "c09_circled_one",
        "operation": "normalize_text",
        "form": "NFKC",
        "text": "\u2460",
        "expected_output": "1",
        "expected_bool": None,
        "classification": "success",
        "observation": "circled digit one becoming 1 under NFKC",
        "codepoints_input": ("U+2460",),
        "codepoints_output": ("U+0031",),
    },
    # 10
    {
        "id": "c10_roman_nine",
        "operation": "normalize_text",
        "form": "NFKC",
        "text": "\u2168",
        "expected_output": "IX",
        "expected_bool": None,
        "classification": "success",
        "observation": "roman numeral nine becoming IX under NFKC",
        "codepoints_input": ("U+2168",),
        "codepoints_output": ("U+0049", "U+0058"),
    },
    # 11
    {
        "id": "c11_superscript_five",
        "operation": "normalize_text",
        "form": "NFKC",
        "text": "\u2075",
        "expected_output": "5",
        "expected_bool": None,
        "classification": "success",
        "observation": "superscript five becoming 5 under NFKC",
        "codepoints_input": ("U+2075",),
        "codepoints_output": ("U+0035",),
    },
    # 12
    {
        "id": "c12_fullwidth_a",
        "operation": "normalize_text",
        "form": "NFKC",
        "text": "\uff21",
        "expected_output": "A",
        "expected_bool": None,
        "classification": "success",
        "observation": "fullwidth Ａ becoming ascii A under NFKC",
        "codepoints_input": ("U+FF21",),
        "codepoints_output": ("U+0041",),
    },
    # 13
    {
        "id": "c13_hangul_decompose",
        "operation": "normalize_text",
        "form": "NFD",
        "text": "\uac00",
        "expected_output": "\u1100\u1161",
        "expected_bool": None,
        "classification": "success",
        "observation": "Hangul 가 decomposing to its exact jamo sequence under NFD",
        "codepoints_input": ("U+AC00",),
        "codepoints_output": ("U+1100", "U+1161"),
    },
    # 14
    {
        "id": "c14_hangul_compose",
        "operation": "normalize_text",
        "form": "NFC",
        "text": "\u1100\u1161",
        "expected_output": "\uac00",
        "expected_bool": None,
        "classification": "success",
        "observation": "that jamo sequence composing back to 가 under NFC",
        "codepoints_input": ("U+1100", "U+1161"),
        "codepoints_output": ("U+AC00",),
    },
    # 15
    {
        "id": "c15_combining_reorder",
        "operation": "normalize_text",
        "form": "NFD",
        "text": "a\u0301\u0327",
        "expected_output": "a\u0327\u0301",
        "expected_bool": None,
        "classification": "success",
        "observation": "combining marks with different classes reordering canonically",
        "codepoints_input": ("U+0061", "U+0301", "U+0327"),
        "codepoints_output": ("U+0061", "U+0327", "U+0301"),
        "combining_classes_input": (0, 230, 202),
        "combining_classes_output": (0, 202, 230),
    },
    # 16
    {
        "id": "c16_combining_equal_class_stable",
        "operation": "normalize_text",
        "form": "NFD",
        "text": "x\u0300\u0301",
        "expected_output": "x\u0300\u0301",
        "expected_bool": None,
        "classification": "success",
        "observation": "combining marks with the same class keeping their original relative order",
        "codepoints_input": ("U+0078", "U+0300", "U+0301"),
        "codepoints_output": ("U+0078", "U+0300", "U+0301"),
        "combining_classes_input": (0, 230, 230),
        "combining_classes_output": (0, 230, 230),
    },
    # 17 - bytes rejected at normalize_text
    {
        "id": "c17_bytes_reject_normalize",
        "operation": "normalize_text",
        "form": "NFC",
        "text": b"",
        "expected_output": None,
        "expected_bool": None,
        "classification": "invalid_text",
        "observation": "a bytes value being rejected instead of decoded",
        "expect_exception": "InvalidTextError",
    },
    # 18
    {
        "id": "c18_embedded_nul",
        "operation": "normalize_text",
        "form": "NFC",
        "text": "a\0b",
        "expected_output": "a\0b",
        "expected_bool": None,
        "classification": "success",
        "observation": "an embedded NUL remaining a normal code point",
        "codepoints_input": ("U+0061", "U+0000", "U+0062"),
        "codepoints_output": ("U+0061", "U+0000", "U+0062"),
    },
    # 19
    {
        "id": "c19_zwj_emoji",
        "operation": "codepoints",
        "text": "\U0001f469\u200d\U0001f52c",
        "expected_output": ("U+1F469", "U+200D", "U+1F52C"),
        "expected_bool": None,
        "classification": "success",
        "observation": "an emoji ZWJ sequence being shown as multiple code points without any grapheme claim",
    },
    # 20
    {
        "id": "c20_regional_indicators",
        "operation": "codepoints",
        "text": "\U0001f1fa\U0001f1f8",
        "expected_output": ("U+1F1FA", "U+1F1F8"),
        "expected_bool": None,
        "classification": "success",
        "observation": "regional indicator code points remaining separate code points",
    },
    # 21
    {
        "id": "c21_sharp_s_key",
        "operation": "local_identifier_key",
        "text": "\u00df",
        "expected_output": "ss",
        "expected_bool": None,
        "classification": "success",
        "observation": "ß producing ss through the local key policy",
        "codepoints_input": ("U+00DF",),
        "codepoints_output": ("U+0073", "U+0073"),
    },
    # 22
    {
        "id": "c22_greek_sigma_key_equal",
        "operation": "local_identifier_key_equal",
        "left": "\u03a3",
        "right": "\u03c3",
        "expected_output": None,
        "expected_bool": True,
        "classification": "key_equal",
        "observation": "Greek capital sigma and small sigma producing the same key",
        "codepoints_left": ("U+03A3",),
        "codepoints_right": ("U+03C3",),
    },
    # 23
    {
        "id": "c23_greek_final_sigma_key_equal",
        "operation": "local_identifier_key_equal",
        "left": "\u03c2",
        "right": "\u03c3",
        "expected_output": None,
        "expected_bool": True,
        "classification": "key_equal",
        "observation": "Greek final sigma and small sigma producing the same key",
        "codepoints_left": ("U+03C2",),
        "codepoints_right": ("U+03C3",),
    },
    # 24
    {
        "id": "c24_turkish_dotted_i",
        "operation": "local_identifier_key",
        "text": "\u0130",
        "expected_output": "i\u0307",
        "expected_bool": None,
        "classification": "success",
        "observation": "Turkish capital dotted I producing i + U+0307, not plain i",
        "codepoints_input": ("U+0130",),
        "codepoints_output": ("U+0069", "U+0307"),
    },
    # 25
    {
        "id": "c25_fullwidth_key_equal",
        "operation": "local_identifier_key_equal",
        "left": "\uff21",
        "right": "a",
        "expected_output": None,
        "expected_bool": True,
        "classification": "key_equal",
        "observation": "fullwidth Ａ and ascii lowercase a producing the same key",
        "codepoints_left": ("U+FF21",),
        "codepoints_right": ("U+0061",),
    },
    # 26
    {
        "id": "c26_e_acute_canonical_equal",
        "operation": "canonical_equal",
        "left": "\u00e9",
        "right": "e\u0301",
        "expected_output": None,
        "expected_bool": True,
        "classification": "canonical_equal",
        "observation": "precomposed and decomposed é being canonically equal",
        "codepoints_left": ("U+00E9",),
        "codepoints_right": ("U+0065", "U+0301"),
    },
    # 27
    {
        "id": "c27_angstrom_canonical_equal",
        "operation": "canonical_equal",
        "left": "\u212b",
        "right": "\u00c5",
        "expected_output": None,
        "expected_bool": True,
        "classification": "canonical_equal",
        "observation": "angstrom sign and U+00C5 being canonically equal",
        "codepoints_left": ("U+212B",),
        "codepoints_right": ("U+00C5",),
    },
    # 28
    {
        "id": "c28_ligature_codepoints",
        "operation": "codepoints",
        "text": "\ufb03",
        "expected_output": ("U+FB03",),
        "expected_bool": None,
        "classification": "success",
        "observation": "ligature U+FB03 as a single code point",
        "codepoints_input": ("U+FB03",),
    },
    # 29
    {
        "id": "c29_ffi_codepoints",
        "operation": "codepoints",
        "text": "ffi",
        "expected_output": ("U+0066", "U+0066", "U+0069"),
        "expected_bool": None,
        "classification": "success",
        "observation": "ffi as three separate code points, distinct from the ligature",
        "codepoints_input": ("U+0066", "U+0066", "U+0069"),
    },
    # 30
    {
        "id": "c30_circled_one_compat_equal",
        "operation": "compatibility_equal",
        "left": "\u2460",
        "right": "1",
        "expected_output": None,
        "expected_bool": True,
        "classification": "compatibility_equal",
        "observation": "circled digit one and ascii 1 being compatibility equal",
        "codepoints_left": ("U+2460",),
        "codepoints_right": ("U+0031",),
    },
    # 31
    {
        "id": "c31_e_acute_compat_distinct",
        "operation": "compatibility_equal",
        "left": "\u00e9",
        "right": "e",
        "expected_output": None,
        "expected_bool": False,
        "classification": "compatibility_distinct",
        "observation": "precomposed é and plain e remaining compatibility distinct",
        "codepoints_left": ("U+00E9",),
        "codepoints_right": ("U+0065",),
    },
    # 32
    {
        "id": "c32_strasse_key_equal",
        "operation": "local_identifier_key_equal",
        "left": "Stra\u00dfe",
        "right": "STRASSE",
        "expected_output": None,
        "expected_bool": True,
        "classification": "key_equal",
        "observation": "Straße and STRASSE producing the same local key",
    },
    # 33
    {
        "id": "c33_dotless_i_key_distinct",
        "operation": "local_identifier_key_equal",
        "left": "\u0131",
        "right": "i",
        "expected_output": None,
        "expected_bool": False,
        "classification": "key_distinct",
        "observation": "dotless ı and ascii i producing different keys",
        "codepoints_left": ("U+0131",),
        "codepoints_right": ("U+0069",),
    },
    # 34
    {
        "id": "c34_nfc_idempotent",
        "operation": "is_normalized",
        "form": "NFC",
        "text": "Hello \u00e9",
        "expected_output": None,
        "expected_bool": True,
        "classification": "idempotent",
        "observation": "NFC idempotence",
    },
    # 35
    {
        "id": "c35_nfd_idempotent",
        "operation": "is_normalized",
        "form": "NFD",
        "text": "e\u0301",
        "expected_output": None,
        "expected_bool": True,
        "classification": "idempotent",
        "observation": "NFD idempotence",
    },
    # 36
    {
        "id": "c36_nfkc_idempotent",
        "operation": "is_normalized",
        "form": "NFKC",
        "text": "ffi 1 A",
        "expected_output": None,
        "expected_bool": True,
        "classification": "idempotent",
        "observation": "NFKC idempotence",
    },
    # 37
    {
        "id": "c37_nfkd_idempotent",
        "operation": "is_normalized",
        "form": "NFKD",
        "text": "e\u0301",
        "expected_output": None,
        "expected_bool": True,
        "classification": "idempotent",
        "observation": "NFKD idempotence",
    },
    # 38 - concatenation non-closure
    {
        "id": "c38_concat_not_closed",
        "operation": "concatenation_preserves_form",
        "form": "NFC",
        "left": "a",
        "right": "\u0301",
        "expected_output": None,
        "expected_bool": False,
        "classification": "not_closed_under_concatenation",
        "observation": "two individually NFC strings whose concatenation is not NFC",
        "codepoints_left": ("U+0061",),
        "codepoints_right": ("U+0301",),
        "concat_raw": "a\u0301",
        "concat_normalized": "\u00e9",
    },
    # 39
    {
        "id": "c39_lowercase_nfc_reject",
        "operation": "normalize_text",
        "form": "nfc",
        "text": "x",
        "expected_output": None,
        "expected_bool": None,
        "classification": "invalid_form",
        "observation": "lowercase nfc being rejected",
        "expect_exception": "InvalidFormError",
    },
    # 40
    {
        "id": "c40_unknown_form_reject",
        "operation": "normalize_text",
        "form": "NFQ",
        "text": "x",
        "expected_output": None,
        "expected_bool": None,
        "classification": "invalid_form",
        "observation": "unknown form NFQ being rejected",
        "expect_exception": "InvalidFormError",
    },
    # 41 - codepoints(bytes) reject
    {
        "id": "c41_codepoints_bytes_reject",
        "operation": "codepoints",
        "text": b"x",
        "expected_output": None,
        "expected_bool": None,
        "classification": "invalid_text",
        "observation": "bytes text being rejected",
        "expect_exception": "InvalidTextError",
    },
    # 42 - local_identifier_key(bytearray) reject
    {
        "id": "c42_key_bytearray_reject",
        "operation": "local_identifier_key",
        "text": bytearray(b"x"),
        "expected_output": None,
        "expected_bool": None,
        "classification": "invalid_text",
        "observation": "bytearray text being rejected",
        "expect_exception": "InvalidTextError",
    },
]

# Sanity check at import time (not during runner)
assert len(CASES) == 42, f"manifest must have 42 cases, got {len(CASES)}"
assert len({c["id"] for c in CASES}) == 42, "case ids must be unique"
